[package]
name = "hello-world"
version = "0.1.0"
authors = ["Hubert Figuière <hub@figuiere.net>"]

[dependencies]
glib = { version="0.1.3", features = ["v2_40"] }
gio = { version="0.1.3", features = ["v2_40"] }
gtk = { version="0.1.3", features = ["v3_12"] }

[[bin]]
name = "hello"